version: '3.8'

services:
  backend:
    build: ./backend
    container_name: file_merger_backend
    ports:
      - "7997:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: file_merger_frontend
    ports:
      - "7996:80"
    restart: always
    depends_on:
      - backend